## 1.06 Fitting our Model

* Fit the model/ algorithm on our data and use it to make predictions.

In [3]:
# Standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

___
### 1. Fitting the model to the data.

Different names for:
* `X` = features, feature variables, data
* `y` = labels, targets, target variables

In [4]:
# Import heart disease data
heart_disease = pd.read_csv('data/heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
# Setup random seed
np.random.seed(42)

# Make data
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

# Split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# Fit the model to the data (training the machine learning model)
clf.fit(X_train, y_train)

# Evaluate Random Forest Classifier (use the patterns the model has learned)
clf.score(X_test, y_test)

0.8524590163934426

___
### 2. Make predictions using a machine learning model.

There are two main ways to make predictions:
* `predict()`
* `predict_proba()`

#### predict()

In [7]:
# Use a trained model to make predictions
clf.predict(np.array([1, 7, 8, 3, 4])) # This doesn't work...

/Users/ashleycasanova/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[1. 7. 8. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [8]:
# Let's try to make predictions using a 2D array
X_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [9]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [10]:
# Predictions on our test data is now in the same format as our test labels
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [11]:
# Now we can compare our predictions to the truth labels to evaluate the model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [13]:
# clf.score() returns the mean accuracy on the given test data and labels 
clf.score(X_test, y_test)

0.8524590163934426

The term "accuracy" can have different meanings depending on the context in which it is used. 

1. **Accuracy in Science:**
   - Formula: `Accuracy = 100% - Error Rate`
   - Measures how close observed or measured values are to the actual or expected values in scientific experiments.
   - It quantifies the correctness of measurements or predictions.
   - A higher accuracy indicates a smaller error rate, signifying more precise and reliable data.
   - Commonly used in fields such as experimental science, engineering, and quality control.

>Note: `Error Rate = (|Observed Value - Actual Value|/Actual Value) * 100`

2. **Accuracy in Machine Learning:**
   - Formula: `(Number of Correct Predictions) / (Total Number of Predictions)`
   - Measures the percentage of correctly classified instances in a machine learning model's predictions.
   - It quantifies the model's effectiveness in making correct predictions.
   - A higher accuracy score indicates that the model is better at classifying data correctly.
   - Used in the context of classification tasks and model evaluation in data science and machine learning.

In [ ]:
# Accuracy Formula: Accuracy = 100% - Error Rate
# Error Rate = (|Observed Value - Actual Value|/Actual Value) * 100
error_rates = []

for y_pred in y_preds:
    for y in y_test:
        if y == 1:
            error_rate = abs(y_pred - y)/y
            error_rates.append(error_rate)
        else:
            error_rates.append(0)

mean_error_rate = np.mean(error_rates)
mean_accuracy = 1 - mean_error_rate
print(mean_accuracy) # Not the same as accuracy in ML

0.7592045149153454


In [18]:
# accuracy_score() - accuracy classification score
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

#### predict_proba()

In [19]:
# predict_proba() returns probabilities of a classification label 
# [probability 0, probability 1]
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [20]:
# Let's predict() on the same data...
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

In [21]:
heart_disease['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

#### <span style="color:hotpink">predict() can also be used for regression models</span>

>Note:  Notes are updated below with a new regression model using Sklearn's dataset on california housing. 

>Note: The boston housing dataset is below, however `load_boston` is depreciated in 1.0 and will be removed in 1.2 due to ethical concerns. See [here](https://scikit-learn.org/1.0/modules/generated/sklearn.datasets.load_boston.html) for more info.

In [25]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing; # Imports as dictionary with keys 'data', 'target', 'target_names` and 'feature_names'

In [26]:
housing_df = pd.DataFrame(housing['data'], columns=housing['feature_names'])
housing_df['target'] = housing['target']

In [39]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [32]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X = housing_df.drop("target", axis=1)
y = housing_df['target']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)

model.score(X_test, y_test)

0.8066196804802649

In [33]:
y_preds = model.predict(X_test)
y_preds[:10]

array([0.49384  , 0.75494  , 4.9285964, 2.54029  , 2.33176  , 1.6549701,
       2.34323  , 1.66182  , 2.47489  , 4.8344779])

In [37]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

We can compare `y_preds` and `y_test` using the `Mean Absolute Error`

`Absolute Error = |y_pred - y_test|`

`Mean Absolute Error = Sum of Absolute Errors for each data point / total number of data points`

In [40]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

0.3265721842781009

On average, each of our models predictions is +/- `0.32` different from our test model.

___

In [23]:
# Import boston housing dataset from sklearn 
from sklearn.datasets import load_boston
boston = load_boston()
boston; # imports as dictionary with keys 'data', 'target', and 'feature_names'

In [26]:
# Create dataframe from boston dataset
boston_df = pd.DataFrame(boston['data'], columns=boston['feature_names'])
boston_df['target'] = pd.Series(boston['target'])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

**About the DataSet:**
* This dataset is made up of a bunch of different parameters about different towns in boston.
* Each row is a town and each column is a parameter.
* Price (or target column) is in the thousands.

>Note: For more information on the different features in this dataset [click here](https://scikit-learn.org/stable/datasets/toy_dataset.html#boston-dataset)

In [27]:
from sklearn.ensemble import RandomForestRegressor

# create the data
x = boston_df.drop('target', axis=1)
y = boston_df['target']

# split into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Instantiate and fit model
model = RandomForestRegressor().fit(X_train, y_train)

# Make predictions
y_preds = model.predict(X_test)

In [28]:
y_preds[:10] # predictions

array([45.779, 13.39 , 19.656, 19.018, 15.462, 24.371, 22.214, 14.717,
       22.333,  8.759])

In [30]:
np.array(y_test[:10]) # true values

array([50. , 13. , 18.5, 22.5, 10.2, 23. , 22.2, 13.5, 21.6,  7. ])

In [31]:
# Compare the predictions to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds) # returns average difference between predictions and target values

1.9369901960784308