IMPORTING NUMPY

In [1]:
import numpy as np

DATATYPES & ATTRIBUTES

In [2]:
# NumPy has one main data type --> ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype

dtype('int64')

In [12]:
a2.dtype

dtype('float64')

In [13]:
a3.dtype

dtype('int64')

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
import pandas as pd
df2 = pd.DataFrame(a2)

In [17]:
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [18]:
# df3 = pd.DataFrame(a3)
# ValueError: Must pass 2-d input. shape=(2, 3, 3)

In [19]:
df = pd.DataFrame(a1)
df

0
0  1
1  2
2  3

CREATING ARRAYS

In [20]:
s1 = np.array([1, 2, 3])
s2 = np.array((1, 2, 3))

In [21]:
s1

array([1, 2, 3])

In [22]:
s1.shape, s1.ndim, s1.dtype, type(s1)

((3,), 1, dtype('int64'), numpy.ndarray)

In [23]:
s2

array([1, 2, 3])

In [24]:
s2.shape, s2.ndim, s2.dtype, type(s2)

((3,), 1, dtype('int64'), numpy.ndarray)

In [25]:
# shift and tab within parantheses should open functions doc string... not working here??
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
type(ones)

numpy.ndarray

In [28]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
h = np.arange(0, 10, 2)

In [31]:
h

array([0, 2, 4, 6, 8])

In [32]:
random_int = np.random.randint(10,size=(3,5))
random_int

array([[8, 0, 3, 2, 4],
       [6, 0, 6, 2, 8],
       [8, 8, 6, 7, 0]])

In [33]:
random_num = np.random.rand(3,5)
random_num

array([[0.50152703, 0.44465776, 0.34112122, 0.83492886, 0.99739661],
       [0.93926637, 0.7656305 , 0.05361178, 0.98548623, 0.54335177],
       [0.43834638, 0.72192491, 0.18518819, 0.34191324, 0.69281113]])

In [34]:
rand_num = np.random.random((3,5))
rand_num

array([[0.22772173, 0.75966175, 0.00356181, 0.33875906, 0.17274442],
       [0.5879368 , 0.32903827, 0.22787436, 0.37900273, 0.46355637],
       [0.79745725, 0.22441196, 0.06815299, 0.87608952, 0.15881165]])

In [35]:
random_int,random_num,rand_num

(array([[8, 0, 3, 2, 4],
        [6, 0, 6, 2, 8],
        [8, 8, 6, 7, 0]]),
 array([[0.50152703, 0.44465776, 0.34112122, 0.83492886, 0.99739661],
        [0.93926637, 0.7656305 , 0.05361178, 0.98548623, 0.54335177],
        [0.43834638, 0.72192491, 0.18518819, 0.34191324, 0.69281113]]),
 array([[0.22772173, 0.75966175, 0.00356181, 0.33875906, 0.17274442],
        [0.5879368 , 0.32903827, 0.22787436, 0.37900273, 0.46355637],
        [0.79745725, 0.22441196, 0.06815299, 0.87608952, 0.15881165]]))

In [36]:
a1

array([1, 2, 3])

In [37]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [39]:
a1[0]

1

In [40]:
a1[0], a2[0], a3[0]

(1,
 array([1. , 2. , 3.3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [41]:
a1[1], a2[1], a3[1]

(2,
 array([4. , 5. , 6.5]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [42]:
a2[0,0]

1.0

In [43]:
a3[0,0]

array([1, 2, 3])

In [44]:
a3[0,0,0]

1

In [45]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 1, 5, 9, 7],
         [4, 3, 0, 3, 5],
         [2, 9, 1, 6, 3],
         [4, 5, 5, 7, 3]],

        [[7, 4, 5, 5, 1],
         [7, 1, 8, 7, 0],
         [4, 1, 0, 6, 0],
         [3, 5, 9, 1, 0]],

        [[0, 5, 9, 5, 7],
         [9, 2, 9, 3, 7],
         [4, 9, 8, 2, 9],
         [7, 2, 6, 2, 6]]],


       [[[6, 6, 2, 6, 8],
         [5, 1, 8, 3, 2],
         [4, 4, 2, 6, 9],
         [5, 9, 8, 9, 1]],

        [[7, 5, 1, 1, 0],
         [5, 0, 8, 5, 1],
         [9, 3, 0, 0, 4],
         [8, 2, 2, 9, 0]],

        [[9, 0, 4, 4, 6],
         [5, 7, 4, 0, 7],
         [3, 7, 7, 5, 0],
         [1, 5, 6, 3, 9]]]])

In [46]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [47]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,:4]

array([[[[0, 1, 5, 9],
         [4, 3, 0, 3],
         [2, 9, 1, 6],
         [4, 5, 5, 7]],

        [[7, 4, 5, 5],
         [7, 1, 8, 7],
         [4, 1, 0, 6],
         [3, 5, 9, 1]],

        [[0, 5, 9, 5],
         [9, 2, 9, 3],
         [4, 9, 8, 2],
         [7, 2, 6, 2]]],


       [[[6, 6, 2, 6],
         [5, 1, 8, 3],
         [4, 4, 2, 6],
         [5, 9, 8, 9]],

        [[7, 5, 1, 1],
         [5, 0, 8, 5],
         [9, 3, 0, 0],
         [8, 2, 2, 9]],

        [[9, 0, 4, 4],
         [5, 7, 4, 0],
         [3, 7, 7, 5],
         [1, 5, 6, 3]]]])

### Manipulating arrays

Arithmetic

In [48]:
a1

array([1, 2, 3])

In [49]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [50]:
a1+ones

array([2., 3., 4.])

In [51]:
a1-ones

array([0., 1., 2.])

In [52]:
a1*ones

array([1., 2., 3.])

In [53]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [54]:
a1

array([1, 2, 3])

In [55]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [59]:
# a2*a3
# ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3)

In [58]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [60]:
a2T = np.transpose(a2)
a2T.shape

(3, 2)

In [61]:
a2T*a3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3,3) 