IMPORTING NUMPY

In [1]:
import numpy as np

DATATYPES & ATTRIBUTES

In [2]:
# NumPy has one main data type --> ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype

dtype('int64')

In [14]:
a2.dtype

dtype('float64')

In [15]:
a3.dtype

dtype('int64')

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [22]:
import pandas as pd
df2 = pd.DataFrame(a2)

In [23]:
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [21]:
df3 = pd.DataFrame(a3)

ValueError: Must pass 2-d input. shape=(2, 3, 3)

In [24]:
df = pd.DataFrame(a1)
df

0
0  1
1  2
2  3