## 1.12 Sorting Arrays

In [2]:
import pandas as pd
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [6]:
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[0, 5, 9],
       [2, 2, 4],
       [5, 5, 9],
       [9, 9, 6],
       [8, 1, 4]])

In [9]:
# np.sort() sorts the array in place
np.sort(random_array)

array([[0, 5, 9],
       [2, 2, 4],
       [5, 5, 9],
       [6, 9, 9],
       [1, 4, 8]])

In [10]:
# np.argsort() returns the indices of the sorted array
np.argsort(random_array)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [2, 0, 1],
       [1, 2, 0]])

In [11]:
a1

array([1, 2, 3])

In [12]:
# Return the indices that would sort the array a1
np.argsort(a1)

array([0, 1, 2])

In [14]:
# No axis
# argmin() returns the index of the minimum value
np.argmin(a1)

0

In [3]:
import numpy as np
a1 = np.array([1,2,3])
np.argmax(a1)

2

In [15]:
random_array

array([[0, 5, 9],
       [2, 2, 4],
       [5, 5, 9],
       [9, 9, 6],
       [8, 1, 4]])

In [19]:
# Down the vertical
# argmax() returns the indeces of the maximum values along an axis
np.argmax(random_array, axis=1)

array([2, 2, 2, 0, 0])

In [17]:
# Across the horizontal
np.argmin(random_array, axis=0)

array([0, 4, 1])