## 1.13 Turning Images into NumPy Arrays

<img src="numpy-panda.png" alt="photo of a panda waving" height=100>

In [2]:
from matplotlib.image import imread

panda = imread('numpy-panda.png')
print(type(panda))

<class 'numpy.ndarray'>


In [3]:
panda.shape

(2330, 3500, 3)

In [4]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

<img src="numpy-car-photo.png" alt="photo of a car" height="100">

In [7]:
car = imread("numpy-car-photo.png")
car.shape

(431, 575, 4)

In [8]:
car[:,:,:3].shape

(431, 575, 3)

<img src="numpy-dog-photo.png" alt="photo of a dog" height="100">

In [9]:
dog = imread("numpy-dog-photo.png")
dog.shape

(432, 575, 4)

In [10]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

<img src="moose.png" alt="picture of moose" height="100">

In [17]:
moose = imread("moose.png")
moose.shape

(4032, 3024, 4)

In [18]:
moose

array([[[0.12941177, 0.12941177, 0.12156863, 1.        ],
        [0.13725491, 0.13725491, 0.12941177, 1.        ],
        [0.1882353 , 0.1882353 , 0.18039216, 1.        ],
        ...,
        [0.44313726, 0.4       , 0.32156864, 1.        ],
        [0.4117647 , 0.3764706 , 0.29411766, 1.        ],
        [0.3882353 , 0.35686275, 0.27450982, 1.        ]],

       [[0.1764706 , 0.1764706 , 0.16862746, 1.        ],
        [0.17254902, 0.17254902, 0.16470589, 1.        ],
        [0.20392157, 0.20392157, 0.19607843, 1.        ],
        ...,
        [0.43529412, 0.39215687, 0.3137255 , 1.        ],
        [0.41568628, 0.38039216, 0.29803923, 1.        ],
        [0.39607844, 0.3647059 , 0.28235295, 1.        ]],

       [[0.22352941, 0.22745098, 0.21176471, 1.        ],
        [0.21568628, 0.21960784, 0.20392157, 1.        ],
        [0.23529412, 0.23921569, 0.22352941, 1.        ],
        ...,
        [0.40784314, 0.3647059 , 0.28627452, 1.        ],
        [0.40784314, 0.372549