## 1.3 Creating Numpy Arrays

In [2]:
import numpy as np

`np.array()` is a function that creates a numpy array.  
`np.ones()` creates a numpy array filled with ones.  
`np.zeros()` creates a numpy array filled with zeros.  
`np.random.rand()` creates a numpy array filled with random numbers.  
`np.random.randint()` creates a numpy array filled with random integers.  
`np.random.seed()` sets the seed for the random number generator.  
`np.unique()` returns the unique values in an array.  

In [48]:
# Create a simple array
# np.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
simple_array = np.array(([1, 2, 3]))
simple_array

array([1, 2, 3])

In [49]:
# HELP!!!!!!!!!!!!!
# We can also use parentheses instead of square brackets for the first parameter.
# In general, lists displayed using parentheses (tuples) are imutable, but not in practice??
simple_array = np.array((1, 2, 3))
simple_array[1] = 10
simple_array

array([ 1, 10,  3])

In [52]:
# we can check the type of the array using .dtype
simple_array, simple_array.dtype

(array([ 1, 10,  3]), dtype('int64'))

In [51]:
# Create an array of ones
# np.ones(shape, dtype=float, order='C')
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# The default type is `float64`
ones.dtype

dtype('float64')

In [56]:
# You can change the datatype with .astype()
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [58]:
# Create an array of zeros
# np.zeros(shape, dtype=float, order='C')
zeros = np.zeros((2, 3, 4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [59]:
zeros.dtype

dtype('float64')

In [60]:
# Create an array within a range of values
# np.arange(start, stop, step, dtype=None)
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [62]:
# Create a random array
# np.random.randint(low, high=None, size=None, dtype='l')
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[2, 0, 2],
       [9, 7, 1],
       [0, 4, 1],
       [0, 9, 2],
       [6, 0, 7]])

In [ ]:
# Random array of floats between 0 and 1
