## 1.3 Creating Numpy Arrays

In [2]:
import numpy as np

`np.array()` is a function that creates a numpy array.  
`np.ones()` creates a numpy array filled with ones.  
`np.zeros()` creates a numpy array filled with zeros.  
`np.random.rand()` creates a numpy array filled with random numbers.  
`np.random.randint()` creates a numpy array filled with random integers.  
`np.random.seed()` sets the seed for the random number generator.  
`np.unique()` returns the unique values in an array.  

In [48]:
# Create a simple array
# np.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
simple_array = np.array(([1, 2, 3]))
simple_array

array([1, 2, 3])

In [49]:
# HELP!!!!!!!!!!!!!
# We can also use parentheses instead of square brackets for the first parameter.
# In general, lists displayed using parentheses (tuples) are imutable, but not in practice??
simple_array = np.array((1, 2, 3))
simple_array[1] = 10
simple_array

array([ 1, 10,  3])

In [52]:
# we can check the type of the array using .dtype
simple_array, simple_array.dtype

(array([ 1, 10,  3]), dtype('int64'))

In [51]:
# Create an array of ones
# np.ones(shape, dtype=float, order='C')
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# The default type is `float64`
ones.dtype

dtype('float64')

In [56]:
# You can change the datatype with .astype()
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [58]:
# Create an array of zeros
# np.zeros(shape, dtype=float, order='C')
zeros = np.zeros((2, 3, 4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [59]:
zeros.dtype

dtype('float64')

In [60]:
# Create an array within a range of values
# np.arange(start, stop, step, dtype=None)
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [62]:
# Create a random array
# np.random.randint(low, high=None, size=None, dtype='l')
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[2, 0, 2],
       [9, 7, 1],
       [0, 4, 1],
       [0, 9, 2],
       [6, 0, 7]])

In [72]:
# Random array of floats between 0 and 1
# np.random.random(size=None, dtype=None, out=None)

np.random.random((5, 3))

array([[0.81170117, 0.82109689, 0.55272172],
       [0.11446705, 0.6545049 , 0.92723329],
       [0.91285328, 0.35280393, 0.4917755 ],
       [0.09434156, 0.80159669, 0.87043239],
       [0.22401374, 0.17524739, 0.96896959]])

In [74]:
# Random 5x3 array of floats between 0 and 1, similar to above
# np.random.rand(size=None, dtype=None, out=None)
np.random.rand(5, 3)

array([[0.17754862, 0.10363402, 0.40464935],
       [0.67324427, 0.6259538 , 0.68522282],
       [0.59546047, 0.24115764, 0.50305453],
       [0.53131816, 0.36400664, 0.63997459],
       [0.92087787, 0.74238169, 0.97986066]])

We can create a numpy array containing pseudorandom numbers using the `np.random.seed()` function.  
This is useful for consistency in testing.  
Setting the seed allows us to get the same random numbers every time we run the code.

In [76]:
# Set random seed equal to 0
# np.random.seed(seed=0)
np.random.seed(0)

# Make 'random' numbers
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [88]:
import pandas as pd

np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5, 3)))
df

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

In [89]:
# Exercise: What numpy function would you use to find the uniwue values in the array below?

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])