## 1.4 Numpy Random Seed

In [1]:
import numpy as np
import pandas as pd

We can create a numpy array containing pseudorandom numbers using the `np.random.seed()` function.  

Pseudo random numbers are generated using a seed value. The seed value is used to generate the same sequence of numbers every time.  


This is useful for consistency in testing and reproducing results.

In [2]:
# Set random seed equal to 0
# np.random.seed(seed=0)
np.random.seed(0)

# Make 'random' numbers
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
# We can generate the same random numbers in a pandas data frame
np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5, 3)))
df

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

With `np.random.seed()` set, we will get the same sequence of random numbers every time we run the notebook.  

What if `np.random.seed()` is not set?

Every time we run the notebook, we will get different random numbers.

In [3]:
# Make more random numbers
np.random.randint(10, size=(5, 3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

Lets see what happens when we set the seed to 0 again.

In [4]:
np.random.seed(0)
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

Because we are setting the seed to 0, we will get the same sequence of random numbers every time we run the notebook.

Setting `np.random.seed()` is not necessary, but is helpful to keep numbers the same throughout your experiments.