## 1.6.6 Comparison Operators

In [1]:
import pandas as pd
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [3]:
a1

array([1, 2, 3])

In [4]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [6]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [7]:
a1 > 5

array([False, False, False])

In [8]:
a1 == a1

array([ True,  True,  True])

In [9]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])