## 1.6.3 Reshape and Transpose

In [1]:
import pandas as pd
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

___
Reshaping

In [3]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a2.shape

(2, 3)

In [5]:
# a2 + a3
# ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [6]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [7]:
a2.reshape(2, 3, 1)  + a3

array([[[ 2. ,  3. ,  4. ],
        [ 6. ,  7. ,  8. ],
        [10.3, 11.3, 12.3]],

       [[14. , 15. , 16. ],
        [18. , 19. , 20. ],
        [22.5, 23.5, 24.5]]])

___
Transpose

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a2.shape

(2, 3)

In [10]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [11]:
a2.T.shape

(3, 2)

In [12]:
matrix = np.random.random(size=(5,3,3))
matrix

array([[[0.40739083, 0.55469899, 0.18135365],
        [0.09035035, 0.82616891, 0.72003283],
        [0.83085026, 0.38586319, 0.8765061 ]],

       [[0.03514049, 0.07100319, 0.51525755],
        [0.8959371 , 0.0604263 , 0.29361292],
        [0.08931676, 0.86453377, 0.4955413 ]],

       [[0.96112475, 0.02317856, 0.88087593],
        [0.28086353, 0.81696692, 0.87249593],
        [0.16613583, 0.88799109, 0.93650531]],

       [[0.18456826, 0.2583786 , 0.17907765],
        [0.34836654, 0.79157325, 0.59981736],
        [0.30542966, 0.88522503, 0.32065531]],

       [[0.36712767, 0.93796476, 0.72061424],
        [0.37786163, 0.76996214, 0.65970642],
        [0.33335129, 0.04332823, 0.72971368]]])

In [13]:
matrix.shape

(5, 3, 3)

In [14]:
matrix.T

array([[[0.40739083, 0.03514049, 0.96112475, 0.18456826, 0.36712767],
        [0.09035035, 0.8959371 , 0.28086353, 0.34836654, 0.37786163],
        [0.83085026, 0.08931676, 0.16613583, 0.30542966, 0.33335129]],

       [[0.55469899, 0.07100319, 0.02317856, 0.2583786 , 0.93796476],
        [0.82616891, 0.0604263 , 0.81696692, 0.79157325, 0.76996214],
        [0.38586319, 0.86453377, 0.88799109, 0.88522503, 0.04332823]],

       [[0.18135365, 0.51525755, 0.88087593, 0.17907765, 0.72061424],
        [0.72003283, 0.29361292, 0.87249593, 0.59981736, 0.65970642],
        [0.8765061 , 0.4955413 , 0.93650531, 0.32065531, 0.72971368]]])

In [15]:
matrix.T.shape

(3, 3, 5)