## 1.6.3 Reshape and Transpose

In [1]:
import pandas as pd
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

___
Reshaping

In [3]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a2.shape

(2, 3)

In [5]:
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [6]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [8]:
a2.reshape(2, 3, 1)  + a3

array([[[ 2. ,  3. ,  4. ],
        [ 6. ,  7. ,  8. ],
        [10.3, 11.3, 12.3]],

       [[14. , 15. , 16. ],
        [18. , 19. , 20. ],
        [22.5, 23.5, 24.5]]])

___
Transpose

In [9]:
a2.shape

(2, 3)

In [10]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [11]:
a2.T.shape

(3, 2)

In [12]:
matrix = np.random.random(size=(5,3,3))
matrix

array([[[0.03474548, 0.98856243, 0.81152063],
        [0.66405945, 0.34704026, 0.68172231],
        [0.52999853, 0.76768998, 0.17628595]],

       [[0.71967495, 0.74862508, 0.91098026],
        [0.96781406, 0.66106726, 0.70157019],
        [0.18212679, 0.71991041, 0.19398089]],

       [[0.12224832, 0.54772953, 0.55576729],
        [0.96007271, 0.21479102, 0.10787925],
        [0.85090817, 0.5330999 , 0.12503336]],

       [[0.67331217, 0.4331244 , 0.48128185],
        [0.87398059, 0.93251162, 0.82313627],
        [0.38217503, 0.56285195, 0.74091632]],

       [[0.15886716, 0.89057136, 0.72712645],
        [0.63659674, 0.39034158, 0.92298486],
        [0.02347766, 0.16306248, 0.28753563]]])

In [13]:
matrix.shape

(5, 3, 3)

In [14]:
matrix.T

array([[[0.03474548, 0.71967495, 0.12224832, 0.67331217, 0.15886716],
        [0.66405945, 0.96781406, 0.96007271, 0.87398059, 0.63659674],
        [0.52999853, 0.18212679, 0.85090817, 0.38217503, 0.02347766]],

       [[0.98856243, 0.74862508, 0.54772953, 0.4331244 , 0.89057136],
        [0.34704026, 0.66106726, 0.21479102, 0.93251162, 0.39034158],
        [0.76768998, 0.71991041, 0.5330999 , 0.56285195, 0.16306248]],

       [[0.81152063, 0.91098026, 0.55576729, 0.48128185, 0.72712645],
        [0.68172231, 0.70157019, 0.10787925, 0.82313627, 0.92298486],
        [0.17628595, 0.19398089, 0.12503336, 0.74091632, 0.28753563]]])

In [15]:
matrix.T.shape

(3, 3, 5)