## 1.6.4 Dot Product vs Element Wise

In [1]:
import numpy as np

In [3]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

mat1.shape, mat2.shape

((3, 3), (3, 2))

In [4]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [5]:
mat2

array([[4, 7],
       [6, 8],
       [8, 1]])

In [6]:
np.dot(mat1, mat2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [8]:
np.random.seed(0)
mat3 = np.random.randint(10, size=(4,3))
mat4 = np.random.randint(10, size=(4,3))
mat3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [9]:
mat4

array([[8, 8, 1],
       [6, 7, 7],
       [8, 1, 5],
       [9, 8, 9]])

In [10]:
np.dot(mat3, mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [13]:
mat3.shape, mat4.shape

((4, 3), (4, 3))

In [14]:
mat3.T.shape, mat4.shape

((3, 4), (4, 3))

In [12]:
np.dot(mat3.T, mat4)

array([[118,  96,  77],
       [145, 110, 137],
       [148, 137, 130]])

In [15]:
# Element-wise multiplication (Hadamard product)
mat3 * mat4

array([[40,  0,  3],
       [18, 49, 63],
       [24,  5, 10],
       [36, 56, 54]])