## 1.6.1 Arithmetic
___

In [1]:
import pandas as pd
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

___
### **Arithmetic**

In [3]:
a1, a1.shape

(array([1, 2, 3]), (3,))

In [4]:
ones = np.ones(3)
ones, ones.shape

(array([1., 1., 1.]), (3,))

In [5]:
# Add two arrays
a1 + ones

array([2., 3., 4.])

In [6]:
# Subtract two arrays
a1 - ones

array([0., 1., 2.])

In [7]:
# Multiply two arrays
a1 * ones

array([1., 2., 3.])

In [8]:
# Multiply a1 and a2
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [9]:
a1.shape, a2.shape

((3,), (2, 3))

In [10]:
# multiply a2 and a3
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [11]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [13]:
# Exercise: How could we reshape a2 to be compatible with a3?
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [14]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [ ]:
# Divide two arrays
a1 / ones

In [ ]:
# Divide using floor division - removes the decimals (rounds down)
a2 // a1

In [ ]:
# Take an array to a power
a1 ** 2

In [ ]:
# You can also use np.square()
np.square(a1)

In [ ]:
# Modulus divide (what is the remainder)
a1 % 2

In [ ]:
# Find the log of an array
np.log(a1)

In [ ]:
# Find the exponential of an array
np.exp(a1)

___
**Broadcasting**

Broadcasting is the way in which numpy carries out arithmetic operations on matricies of different sizes.

NumPy operations on arrays of the same size use an element-wise approach.

In [ ]:
# Example: 
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

a * b

For arrays of differing sizes, smaller arrays are "broadcast" across the larger array in accordance with vector rules.

This approach increases efficiency as it can be carried out without making needless coppies of data.

In [ ]:
# For example:
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a * b

Two Dimensions are compatible when
1. they are equal, or
2. one of them is 1

We can reshape arrays to be compatible with each other...

In [ ]:
x = np.arange(4)
x

In [ ]:
y = np.ones(5)
y

In [ ]:
x + y

In [ ]:
x.shape, y.shape

In [ ]:
xx = x.reshape(4,1)
xx, xx.shape

In [ ]:
xx.shape, y.shape

In [ ]:
xx + y