## 1.6.5 Exercise Nutbutter Store Sales

In [3]:
import numpy as np
import pandas as pd

In [4]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [8]:
weekly_sales = pd.DataFrame(sales_amounts,
                            index=['Mon', 'Tues', 'Wed', 'Thurs', 'Fri'],
                            columns=['Almond butter', 'Peanut butter', 'Cashew butter'])

weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [9]:
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [10]:
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=['Price'],
                              columns=['Almond butter', 'Peanut butter', 'Cashew butter'])

butter_prices.shape

(1, 3)

In [22]:
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [11]:
weekly_sales.shape

(5, 3)

In [12]:
# Find total sales for one day
total_sales = prices.dot(sales_amounts)
total_sales

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

The shapes aren't aligned, we need the middle two numbers to be the same.

In [13]:
prices.shape, sales_amounts.shape

((3,), (5, 3))

In [23]:
prices

array([10,  8, 12])

In [25]:
sales_amounts.T

array([[12,  3,  9,  4,  1],
       [15,  3, 19,  6,  6],
       [ 0,  7, 18, 12,  7]])

In [27]:
((10*12) + (8*15) + (12*0)), ((10*3) + (8*3) + (12*7)), ((10*9) + (8*19) + (12*18)), ((10*4) + (8*6) + (12*12)), ((10*1) + (8*6) + (12*7))

(240, 138, 458, 232, 142)

In [16]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [18]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [20]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [21]:
weekly_sales['Total'] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total
Mon               12             15              0    240
Tues               3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142